#!/bin/bash
if [[ $# -ne 2 ]]; then
	echo "Need exactrly two arguments"
	exit 1
fi

length_1=${#1}
length_2=${#2}

if [[ $length_1 -gt $length_2 ]]; then 
	echo "$1 is longest"
elif [[ $length_1 -eq $length ]]; then
	echo "string are equal"
else
	echo "$2 is longest"
fi

exit 0


