#!/bin/bash

if [[ ! $1 ]]; then
	echo "Missing argument" >&2
	exit 1
fi

declare open_editor=""
if [[ $# -eq 1 ]]; then
	open_editor="true"
fi

declare -r bindir="${HOME}/bin"

#check bin directory exists 
if [[ ! -d $bindir ]]; then
	if mkdir "$bindir"; then
		echo "created ${bindir}" >&2
	else

	 	echo "could not create ${bindir}" >&2
		exit 1
	fi
fi

while [[ $1 ]]; do
	scriptname="$1"
	filename="${bindir}/${scriptname}"
	
	if [[ -e $filename ]]; then
		echo " File ${filename} already exists" >&2
		shift
		continue
	fi

	if type "$scriptname" > /dev/null 2>&1; then
		echo "There is already a command with ${scriptname}" >&2
		shift
		continue
	fi
	
	#Create script
	echo '#!/bin/bash' >> "$filename"
	# Add exe permission
	chmod u+x "$filename"

	shift
done

#open with editor

if [[ $open_editor ]]; then
	echo opening
	if [[ $EDITOR ]]; then
		$EDITOR "$filename"
	else
		echo "script created not startig because we dont have default editor set" >&2	     fi
fi
fi

exit 0
